# Clippy 配置文件
# 更多配置选项请参考: https://rust-lang.github.io/rust-clippy/

warn-on-all-wildcard-imports = true
too-many-arguments-threshold = 7
too-large-for-stack = 100
max-fn-params-bools = 4
cognitive-complexity-threshold = 28
