[package]
name = "pingora_proxy"
version.workspace = true
edition = "2024"

[dependencies]
pingora = { version = "0.6.0", features = ["lb"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

[[bin]]
name = "pingora_proxy"
path = "src/main.rs"
